### PR TITLE
Gracefully handle NPEs that occur if a given secret has been modified…

### LINKED ISSUE #45: NPE if secret is missing username or password
If the secret gets overwritten incompletely (in our case missing username) then retry results in NullPointerException at
https://github.com/aws/aws-secretsmanager-jdbc/blob/master/src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerDriver.java#L325

### PR DESCRIPTION
**Pull request by kendrabach**
… to the point of invalidation outside of the driver's scope

*Issue #, if available:*
fixes #45

*Description of changes:*
Change gracefully handles NullPointerExceptions that may occur after a previously valid secret has been modified outside of the driver's scope to the point of invalidation (ie. missing username or other parameters required to construct driver URL). In this scenario going forward, users can expect to receive a RuntimeException instead. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by madsid — APPROVED** [review]
LGTM

File: src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerDriver.java [hunk 1]
```diff
@@ -376,22 +376,23 @@ public Connection connect(String url, Properties info) throws SQLException {
...
-                throw new IllegalArgumentException("URL " + url + " is not a valid URL starting with scheme " +
-                        SCHEME + " or a valid retrievable secret ID ");
-            }
-
             try {
+                String secretString = secretCache.getSecretString(url);
+                if (StringUtils.isNullOrEmpty(secretString)) {
+                    throw new IllegalArgumentException("URL " + url + " is not a valid URL starting with scheme " +
+                            SCHEME + " or a valid retrievable secret ID ");
+                }
```
Comment (danmancuso) [inline src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerDriver.java:384]: I'm not sure this fixes the original issue.  If 'username' or 'password' is missing in the JSON, in lines [343-344](https://github.com/aws/aws-secretsmanager-jdbc/blob/master/src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerDriver.java#L344), then JSON Node will return 'null', and we'll get a nullException, which isn't caught anywhere. 

We'll want to handle no username or password up there too.

**Review by danmancuso — CHANGES_REQUESTED** [review]

File: src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerDriver.java (hunk 1 above)
Comment (kendrabach) [reply src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerDriver.java:384]: The lines you pointed to are within the private connectWithSecret method. This method is only invoked after the [secretCache.getSecretString(url)](https://github.com/aws/aws-secretsmanager-jdbc/blob/master/src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerDriver.java#L379) call is made on Line 379. This call results in an NPE if a previously valid secret is modified outside of the driver flow to remove the username or password parameter (as described in the original issue) and never makes it to the connectWithSecret call on line 402.

Comment (kendrabach) [reply src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerDriver.java:386]: @danmancuso as we discussed offline, there appears to be 2 separate NPE opportunities here that need addressed:
1. In the public connect method if a secret's username and/or password _value_ has been removed 
2. In the private method if the username and/or password fields are removed entirely (removal of _key and value_)

Commit 1 addresses the first while commit 2 addresses the second.

**Review by danmancuso — APPROVED** [review]
